---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec
  format: doc

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[custom_app::default]
    attributes:
