---
driver:
  name: dokken
  chef_version: latest
  privileged: true

transport:
  name: dokken

provisioner:
  name: dokken
  client_rb:
    environment: kitchen

verifier:
  name: inspec
  format: doc

platforms:
  - name: centos-7
    driver:
      image: centos:7.2.1511
      intermediate_instructions:
        - RUN yum clean all
        - RUN yum swap fakesystemd systemd
        - RUN yum -y install net-tools lsof
      pid_one_command: /usr/lib/systemd/systemd

suites:
  - name: default
    run_list:
      - recipe[custom_app::default]
