sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-precise
    packages:
      - chefdk

cache: apt

services: docker

env:
  matrix:
    - INSTANCE=default-centos-7

# Don't bundle install
install: echo 'skip bundle install'

# Make sure we use ChefDK's ruby
before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef gem install kitchen-dokken

script:
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/rubocop --version
  - /opt/chefdk/embedded/bin/rubocop
  - /opt/chefdk/embedded/bin/foodcritic --version
  - /opt/chefdk/embedded/bin/foodcritic . --exclude spec -f any -t ~FC064 -t ~FC065 -t ~FC019
  - /opt/chefdk/embedded/bin/rspec -f doc
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen test ${INSTANCE}
