name 'custom_app'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures custom_app'
long_description 'Installs/Configures custom_app'
version '0.1.0'

depends 'custom_ruby'
depends 'git'
